// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDicP5oAPCNoouBWQ1uBFiTfLpfC5y6NC8',
    appId: '1:662658703999:web:6d7730cfd3e87dc885954a',
    messagingSenderId: '662658703999',
    projectId: 'work-snap',
    authDomain: 'work-snap.firebaseapp.com',
    storageBucket: 'work-snap.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDArK6JJayh-iYzFeTRyW_WSf64xQ3pPGE',
    appId: '1:662658703999:android:8f0d5059ae13b02285954a',
    messagingSenderId: '662658703999',
    projectId: 'work-snap',
    storageBucket: 'work-snap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC20XmnMCxm8t3gryntECL4SXGcdETKAuI',
    appId: '1:662658703999:ios:5b6c64ad641ced2085954a',
    messagingSenderId: '662658703999',
    projectId: 'work-snap',
    storageBucket: 'work-snap.firebasestorage.app',
    iosBundleId: 'com.jeankpoti.doit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC20XmnMCxm8t3gryntECL4SXGcdETKAuI',
    appId: '1:662658703999:ios:018edcca1848140685954a',
    messagingSenderId: '662658703999',
    projectId: 'work-snap',
    storageBucket: 'work-snap.firebasestorage.app',
    iosBundleId: 'com.jeankpoti.doIt.doIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDicP5oAPCNoouBWQ1uBFiTfLpfC5y6NC8',
    appId: '1:662658703999:web:933baf46f2d16f2e85954a',
    messagingSenderId: '662658703999',
    projectId: 'work-snap',
    authDomain: 'work-snap.firebaseapp.com',
    storageBucket: 'work-snap.firebasestorage.app',
  );
}
